// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: BankAccount.proto

/*
Package Bank is a generated protocol buffer package.

It is generated from these files:
	BankAccount.proto

It has these top-level messages:
	EmptyRequest
	NewAccount
	Account
	Response
	AccountBalance
	Event
	Deposit
	WithDraw
	Transfer
*/
package Bank

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BankService service

type BankServiceClient interface {
	CreateAccount(ctx context.Context, in *NewAccount, opts ...client.CallOption) (*Response, error)
}

type bankServiceClient struct {
	c           client.Client
	serviceName string
}

func NewBankServiceClient(serviceName string, c client.Client) BankServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "Bank"
	}
	return &bankServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *bankServiceClient) CreateAccount(ctx context.Context, in *NewAccount, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BankService.CreateAccount", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BankService service

type BankServiceHandler interface {
	CreateAccount(context.Context, *NewAccount, *Response) error
}

func RegisterBankServiceHandler(s server.Server, hdlr BankServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&BankService{hdlr}, opts...))
}

type BankService struct {
	BankServiceHandler
}

func (h *BankService) CreateAccount(ctx context.Context, in *NewAccount, out *Response) error {
	return h.BankServiceHandler.CreateAccount(ctx, in, out)
}
